Repository ynput/ayon-photoshop, pull requests merged in 2025-04, with the labels that each got.

#27 Support tga format for publishing image product type.
  client/ayon_photoshop/api/extension/host/index.jsx
  client/ayon_photoshop/plugins/publish/extract_image.py
  server/settings/publish_plugins.py
Labels: type: enhancement, sponsored

#28 Chore: Update ffmpeg commands
  client/ayon_photoshop/plugins/publish/extract_review.py
Labels: type: bug

#29 Feature: Auto install extension
  client/ayon_photoshop/hooks/pre_launch_install_ayon_extension.py
  client/pyproject.toml
  server/settings/main.py
Labels: type: enhancement, community
